// this dictionary exists to assist the system with associating the svg images with currency codes using a 2 digit identifier of the country
// the keys in this dictionary can be mapped to .svg files in the src/public/svgs folder.
// exportable to different JS files
export const countryCurrencyMap = {
    eu: "EUR",
    us: "USD",
    jp: "JPY",
    bg: "BGN",
    cz: "CZK",
    dk: "DKK",
    gb: "GBP",
    hu: "HUF",
    pl: "PLN",
    ro: "RON",
    se: "SEK",
    ch: "CHF",
    is: "ISK",
    no: "NOK",
    hr: "HRK",
    ru: "RUB",
    tr: "TRY",
    au: "AUD",
    br: "BRL",
    ca: "CAD",
    cn: "CNY",
    hk: "HKD",
    id: "IDR",
    il: "ILS",
    in: "INR",
    kr: "KRW",
    mx: "MXN",
    my: "MYR",
    nz: "NZD",
    ph: "PHP",
    sg: "SGD",
    th: "THB",
    za: "ZAR",
};